version: '3.0'
services:
  #   backend:
  #     build: .
  #     container_name: crud_python
  #     command: run dev
  #     working_dir: /app
  #     volumes:
  #       - ./src:/app/src
  #     ports:
  #       - 3001:3001
  db:
    container_name: crud_python_db
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_DATABASE: crud_python_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
